#!/bin/bash -ex

dl() {
    cd $3; curl -L -f $2 -o $1; cd -
}

VERSION="2-5-28"
FILE="joomla_${VERSION}-stable-full_package.tar.gz"
J_PATH="joomla25/${VERSION}/joomla_${VERSION}-stable-full_package-tar-gz"
URL="https://downloads.joomla.org/cms/${J_PATH}?format=gz"

dl $FILE $URL /usr/local/src

